#:schema node_modules/wrangler/config-schema.json
name = "vibetoprod"
main = "functions/[[route]].ts"
compatibility_date = "2024-09-23"
assets = { directory = "dist" }

[vars]
CLOUDFLARE_ACCOUNT_ID = "5b25778cf6d9821373d913f5236e1606"
AI_GATEWAY_ID = "vibetoprod-ai"

[env.production.vars]
ENVIRONMENT = "production"
CLOUDFLARE_ACCOUNT_ID = "5b25778cf6d9821373d913f5236e1606"
AI_GATEWAY_ID = "vibetoprod-ai"

[env.development.vars]
ENVIRONMENT = "development"
CLOUDFLARE_ACCOUNT_ID = "5b25778cf6d9821373d913f5236e1606"
AI_GATEWAY_ID = "vibetoprod-ai"


# For local development, you can use:
# wrangler pages dev dist --compatibility-date=2024-07-29